### 网关参数 ###
# 目前仅支持模拟单一值
client-id: "12345678"
shared-secret: "shared secret"
# 是否校验登录，如果登录如法验证通过，设置未false
auth-check: false
# 见SMGP协议，48表示3.0 即 0x30 = 0011 0000；19表示1.3 即 0x13 = 0001 0011；32表示2.0 即 0x20 = 0010 0000
version: 48
# 最大连接数
max-cons: 10
# 心跳报文发送间隔
active-test-duration: 60s
# 多节点部署时使用，datacenter-id 取值 [0,3]
datacenter-id: 1
# 多节点部署时使用，worker-id 取值 [0,8]
worker-id: 1
# SMGW代码：3字节（BCD 码，取值 6位十进制数）
smgw-id: 100001
# 接收窗口大小
receive-window-size: 512
# 处理消息的任务线程池大小
max-pool-size: 2048

### 以下为MT发送相关参数 ###
sms-display-no: 95566
need-report: 1
# 消息优先级 0-3
priority: 3
service-id: myService
fee-type: 05
fee-code: free
charge-term-id: 95566
fixed-fee:
link-id:
# 短信默认有效期，超过下面配置时长后，如果消息未发送，则不再发送
default-valid-duration: 2h

### 以下是模拟网关运行情况的参数 ###
# 成功率：
# 95  表示 95%
# 99  表示 99%
# 999 表示 99.9%
success-rate: 96
# Mt响应的最大与最小时间，状态报告在fix-report-resp-ms后发送
min-submit-resp-ms: 1
max-submit-resp-ms: 3
fix-report-resp-ms: 5